### ISSUE TITLE
Copyright Notice prints incorrect license

### ISSUE THREAD

**Issue by AThirdPerson** [noirscape/lennytube#1]
Either the copyright notice within the program (line 71) incorrectly lists that the project is licensed under GPLv3 or the project incorrectly lists that it is under the AGPLv3.  

I suspect it's the line itself though, since every other reference to a license mentions the AGPLv3, including the comment at the top.

**Comment by noirscape** [comment]
Oops, sorry. Adjusted (you were corect).
